name: online_quiz
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  image_picker: ^1.1.2
  get: ^4.7.2
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner.png
    - assets/images/banner-2.png
